#!/bin/bash
set -e

FWPATH="../"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

NAME="40_o_47_o_48_o_410_o_411_o_412_o_DAS_RS.bin"
cd $FWPATH
touch main.c
make -j8 build_args='-DHW_VER=40'
cd $DIR
cp $FWPATH/build/BLDC_4_Bootloader.bin $NAME

NAME="60_o_75_300_o_HD60_o_UAVC_OMEGA_o_75_300_R2_o_60_MK3_o_100_250_o_75_300_R3_o_60_MK4_o_60_MK5_o_HD75.bin"
cd $FWPATH
touch main.c
make -j8 build_args='-DHW_VER=60'
cd $DIR
cp $FWPATH/build/BLDC_4_Bootloader.bin $NAME

NAME="generic.bin"
cd $FWPATH
touch main.c
make -j8 build_args='-DHW_VER=0'
cd $DIR
cp $FWPATH/build/BLDC_4_Bootloader.bin $NAME

# Clean
cd $FWPATH
make clean
cd $DIR

